default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bundles_development
  username: postgres
  password: 1234
  host: localhost

test:
  <<: *default
  database: bundles_test
  username: postgres
  password: 1234
  host: localhost

production:
  <<: *default
  url: postgresql://bundles:Pr1THzGCc7OLJQD3bw64H2D0GPgzY9FB@dpg-d36483be5dus73ds03n0-a/bundles
